### ISSUE TITLE
Make a main/sensor screen implement HTML/JS

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#121]
**Problem**
For making the app more generic we will display an HTML file in the sensor list screen.

**Preferred Solution**
Sensor list fragment will contain an Android WebView component. When fragment starts it will load the HTML page which corresponds to the selected device/product. We need to have an HTML file for each device/product we support. We need to define the Javascript interface methods which will support showing the live sensor values in the HTML file, as well as executing Bluetooth Gatt commands like read/write to the characteristic.

**Additional context**
We implemented something similar for the UseCases features.

**Comment by SerhatSurguvec** [comment]
Done
