### ISSUE TITLE
Test unreleased features

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#245]
Unreleased features:
- Add publisher backend share
- Add actions import, export, and share
- Chnage backend resource url
- Add hints to mqtt configuration
- Add publisher backend inport, export
- Fix publisher multiple submit bug
- Add alarm action outcome
- Add publisher backend swipe to delete
- Add AcnSchmersal support
- Add AcnCache support
- Add action timeframe
- Add equal condition to actions
- Add action deactivation
- Small bug fixes
- Small code improvements

If something doesn't work, create an issue.

**Comment by Nicba1010** [comment]
Add publisher backend share: PASS
Notes
 - REST
  - adding headers and get parameters
   - if you dont press done, data isnt saved AND USER ISNT WARNED
   - no swipe to delete
 - after sharing backends after selecting with long click when you get back into app it is still in select mode
Add actions import, export, and share: PASS
Notes
 - after sharing backends after selecting with long click when you get back into app it is still in 
Chnage backend resource url: PASS
Add hints to mqtt configuration: NEED CLARIFICATION
Notes:
 - scrolling by touching the device list first results in incomplete scroll
Add publisher backend import, export: PASS
Fix publisher multiple submit bug: PASS
Add alarm action outcome: TO BE CHECKED
Add AcnSchmersal support: TO BE CHECKED
Add AcnCache support: TO BE CHECKED
Add action timeframe: PASS
Add equal condition to actions: PASS
Add action deactivation: PASS
Small bug fixes: I HOPE
Small code improvements: I HOPE
Add publisher backend swipe to delete: PASS

**Comment by Nicba1010** [comment]
Add alarm action outcome: PASS
Add AcnSchmersal support: PASS
Add AcnCache support: Not yet supported properly
