### ISSUE TITLE
Publisher screen is not filling up after merge

### ISSUE THREAD

**Issue by pascaldornfeld** [aconno/Sensorics#307]
The screen showing a publisher is not filling up anymore after merge of branch publisher-refactoring (pull-request #281). I noticed that _BasePublisherActivity.onCreate()_ has to fill it and it never gets called. The reason is most likely that _onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?)_ was used. @Nicba1010 Is there a specific reason for that?
This is a video of the current situation: https://drive.google.com/open?id=1qEjawM0MGttruphIGlYvMvvgPXEN8wf9

When it gets changed to the usual onCreate method with one param then it crashes on another end which has to be further investigated. Here are some points:

- Notice:
  1. AzureMqttPublisherActvity.onCreate() calls AzureMqttPublisherActvity.initViews()
  2. then AzureMPA.initViews() calls BasePA.initViews()
  3. then AzureMPA.onCreate() calls BasePA.onCreate()
  4. if it gets changed to the onCreate() with one param, it will call initViews() again. Pbly the super.initViews() has to be removed in the AzureMPA class as it is not in the other subclasses of BasePA
  
- The exception when it gets changed to onCreate() with one param is:
  `java.lang.IllegalArgumentException: No view found for id 0x7f0a00ed (com.aconno.sensorics.dev:id/frame) for fragment DeviceSelectFragment`
  
- Before the merge there was another problem when turning the phone off and on quickly (possibly in other situations too): https://drive.google.com/open?id=1h7ae1LVQrOkNT5dZuiIRdVGI-0wUjycR

**Comment by pascaldornfeld** [comment]
Also notice:
Concrete.onCreate() calls Concrete.initViews()
then Concrete.initViews() calls super.initViews()
then Concrete.onCreate() calls super.onCreate()
if it gets changed to the onCreate() with one param, it will call super.initViews() again.

**Comment by pascaldornfeld** [comment]
The exception when it gets changed to onCreate() with one param is:
`java.lang.IllegalArgumentException: No view found for id 0x7f0a00ed (com.aconno.sensorics.dev:id/frame) for fragment DeviceSelectFragment`

**Comment by Nicba1010** [comment]
Ok I have no idea but I will look into it tomorrow @pascaldornfeld I'm sorry I havent been around these couple of days but I have exams and things.

**Comment by Nicba1010** [comment]
Fixed by https://github.com/aconno/Sensorics/pull/309/commits/eb081d6abde2ac15cef2bc984fa9c6cd1046204f
