### ISSUE TITLE
Refactor Permission System

### ISSUE THREAD

**Issue by Nicba1010** [aconno/Sensorics#36]
**Problem**
The permission system as is makes it very clunky to setup multiple actions that require the same permission. It also makes it unable to request multiple permissions at once.

**Preferred Solution**
Refactor system to allow requesting multiple permissions at once.
Allow specifying an anonymous object callback so that not everything gets called back to the activity.

**Comment by Nicba1010** [comment]
@sergiomr88 we don't need it for scanning but we could need it to export some data.
The point is to have something that can work for any permission.

**Comment by borna-mdn** [comment]
For now we don't need support for requesting multiple permissions at once.

**Comment by borna-mdn** [comment]
The issue stays for future requirements
