### ISSUE TITLE
No margins in acnBEACON screen

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#367]
There should be 16dp screen edge margin.

#### Preview:
<img width="338" alt="Screenshot 2020-07-15 at 15 21 29" src="https://user-images.githubusercontent.com/21616462/87550075-ef529f80-c6ae-11ea-8b25-91ec73963337.png">

**Comment by alenmagdic** [comment]
Version of acnBEACON screen that is on server is for some reason broken. I tested it using local version of acnBEACON.html and it works perfectly, as can be seen on the following screenshoot:
![Screenshot_20200716-193636_Sensorics](https://user-images.githubusercontent.com/57095273/87703925-d96ed880-c79b-11ea-98d8-2b917d1324c6.jpg)

**Comment by borna-mdn** [comment]
Fix the server version

**Comment by alenmagdic** [comment]
Fixed it.
