### ISSUE TITLE
MQTT publishing unexpectedly stopped

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#407]
**Describe the bug**
MQTT publishing unexpectedly stops after approximately 30 minutes.

**To Reproduce**
1. Set up MQTT backend in Sensorics
2. Start scanning and observe MQTT publications through MQTT client (eg. MQTT.fx)
3. Observe that after around 30 min publishing stops

**Expected behavior**
Publishing should not stop, and should continue as long as Sensorics app is scanning.

**Smartphone (please complete the following information):**
 - Device: Pixel 2 (Android 10)
 - MQTT client: MQTT.fx (version 1.7.1)

**Comment by vetemi** [comment]
We experience this also with a HTTP backend. 

**Table**:
Device: Samsung Galaxy Tab A (Android 9) 

Sorry, I don't know want to be rude but do you know when you plan to fix it? We want to use your sensors with your app and we're unfortunately blocked to use them because of this behavior.

**Comment by borna-mdn** [comment]
Hi @vetemi. I'll take a look and let you know when to expect the fix.
