### ISSUE TITLE
Exception in ZonedDateTime.parse() in ResolverImpl

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#83]
**Description**
The unhandled exception arises in method ZonedDateTime.parse() in ResolverImpl class.

**To Reproduce**
1. Open the app

**Expected behavior**
App should start without crash.

**Smartphone**
 - Device: Samsung SM-G950F
 - OS: Android 7.0.0, API 24

**Comment by SerhatSurguvec** [comment]
Resolver is no longer needed.
