### ISSUE TITLE
Room data integrity error in 4.1.1 version from the PlayStore

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#96]
**Description**
There is Room data integrity exception in Sensorics 4.1.1 version currently in PlayStore.

**To Reproduce**
1. Have previous version of Sensorics installed
2. Install new version of Sensorics (version 4.1.1) from the Play Store
3. Open the app
4. App crashes

**Expected behavior**
App shouldn't crash when you install newer version of software

**Smartphone**
 - Device: All
 - OS: All
 - Version: All

**Additional context**
When changing Room database schema, need to increase Room database version

**Comment by SerhatSurguvec** [comment]
This will be fixed in the next version. Database version is increased in 139316d6238077d374d32549663b7286581f1246.
